### ISSUE TITLE
[Docker] quickstart does not support external network requests

### ISSUE THREAD

**Issue by unlikelyzero** [yamcs/quickstart#11]
We are attempting to add quickstart to our CI pipeline and noticed that yamcs is not configured for outside network requests by default.

It should be as simple as adding the following to the `etc/yamcs.yml` file:
```yml
address: "0.0.0.0"
```

**Comment by fqqb** [comment]
I don't think the commit in #12 will make a difference, the bind `address` is not specified at top-level, but as an argument of the service `org.yamcs.http.HttpServer`: https://docs.yamcs.org/yamcs-server-manual/services/global/http-server/

Maybe your problem is rather at docker level? In docker-compose.yml, the host port specifies 127.0.0.1, think that can be dropped.

**Comment by unlikelyzero** [comment]
Closed in https://github.com/yamcs/quickstart/pull/13
