### ISSUE TITLE
Algorithms example

### ISSUE THREAD

**Issue by shefalijoshi** [yamcs/quickstart#35]
We are hoping to continue to test yamcs/quickstart as a part of our openmct-yamcs build automation.
As a part of this work, we would like an example of an Algorithm added to the XTCE. This will allow us to test MDB Overrides among other things relevant to algorithms.

**Comment by fqqb** [comment]
Hi, thanks. It's merged now.

Your output parameter was part of the container entries (and so generating errors on each packet due to them not matching the definition), so I fixed that in another commit, as well as the following changes:

* Made all references relative
* Mark Sunsensor_Beta dataSource as "derived" instead of the default "telemetered".
* Removed leading whitespace from the algorithm (looks better in the UI)
