### ISSUE TITLE
docker image yamcs is not available

### ISSUE THREAD

**Issue by Vinalti** [yamcs/quickstart#6]
Hello, 

## Description of the issue
The `docker-compose.yml` file uses the docker image `yamcs` which is no longer available on [docker-hub ](https://hub.docker.com/r/yamcs/yamcs/).

https://github.com/yamcs/quickstart/blob/79ebc692ab0241e6c8f3f42cdb774de276ace55b/docker/docker-compose.yml#L2-L12

When we try to build the image and bring it up, an error occurs, because the image is not available:

```bash
$> docker-compose up
"Pulling yamcs (yamcs:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN] y

Pulling yamcs (yamcs:)...
ERROR: pull access denied for yamcs, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
```

## Recommended Solutions
- Change `image: "yamcs"` with a relevant replacement (e.g. add Dockerfile)
- Provide on docker-hub the yamcs image again

## Notes
I couldn't find a good documentation on [docs.yamcs.org](https://docs.yamcs.org/) about docker containers. Is it still supported ?

**Comment by fqqb** [comment]
Indeed, I pushed a replacement that replaces the instruction `image: yamcs` with `build: .`.

This was the intended previous behaviour too, but I see that the orchestration was done through the Makefile, instead of the compose configuration. Should be better now.

Note that we don't actually provide common DockerHub images for Yamcs (other than some example configurations that are used in unit testing of related components). Reason being that Yamcs is often extended with plugins and/or custom Java components, and so a docker approach is not necessarily the most convenient.
